### ISSUE TITLE
Request: Add this to nixos/nixpkgs

### ISSUE THREAD

**Issue by 06kellyjac** [saschagrunert/kubernix#124]
I've noticed kubernix isn't in nixpkgs but the build is nix based and looks like it'd be pretty easy to adapt for nixpkgs.
Or a new nix file can be written to install based on pulling the binaries from releases ([like firecracker here](https://github.com/NixOS/nixpkgs/blob/4be9fcd1840861dd2c59a21eaf28e9ef5d63d046/pkgs/applications/virtualization/firecracker/default.nix)) if you'd prefer.

I'd be nice to Kubernix to my NixOS config.
Thanks

**Comment by saschagrunert** [comment]
Sounds good: https://github.com/NixOS/nixpkgs/pull/73385

**Comment by 06kellyjac** [comment]
Well that was quick, thanks :)
