### ISSUE TITLE
Provide a package in nixpkgs or nur

### ISSUE THREAD

**Issue by vdemeester** [saschagrunert/kubernix#126]
Hey @saschagrunert, 

Awesome project :tada: :hugs: I was wondering if you wanted to provide kubernix as a package/derivation in [`NixOS/nixpkgs`](https://github.com/NixOS/nixpkgs) or in a [*Nix User Repository*](https://github.com/nix-community/NUR) ?

That would make it even easier to use and adopt :angel:

**Comment by saschagrunert** [comment]
Hey, thank you for the nice feedback :pray:, it's already on its way into nixpkgs: https://github.com/NixOS/nixpkgs/pull/73385

**Comment by ldesgoui** [comment]
Kubernix 0.2.0 is now in nixpkgs-unstable, I believe this can be closed.
