### ISSUE TITLE
Is it possible to transfer docker images to the kubernetes nodes?

### ISSUE THREAD

**Issue by chrissound** [saschagrunert/kubernix#170]
I don't see any docker process running quite strangely. Is there some way I can transfer docker images to the kubernetes "nodes" - so I can later on reference them in deployments etc?

Sorry, much more of question than an issue!

**Comment by saschagrunert** [comment]
Hey 👋, the container runtime for Kubernetes used by kubernix is not docker, it’s CRI-O. When running kubernix, then you can import  images via `crictl pull`. :)

**Comment by chrissound** [comment]
Thanks for the quick response! Hmm, how do I get to the "nodes" though? To for example run `ctr images import...`?

**Comment by saschagrunert** [comment]
Unfortunately this is not that easily possible. You could copy the containers storage in the cri-o directors to each node, but the container runtime interface (CRI) has no functionality for loading images to a single node.

**Comment by saschagrunert** [comment]
Closing. Feel free to reopen if you have further questions.
