### ISSUE TITLE
How to gain access to "nodes" / logs? 

### ISSUE THREAD

**Issue by chrissound** [saschagrunert/kubernix#182]
```
[demo@nixos:~/kubernix]$ KUBERNIX_LOG_LEVEL=debug sudo -E ./target/release/kubernix --nodes=2 -l debug
[ERROR] Timed out waiting for process 'API Server' (kube-apiserver) to become ready
[ERROR] Controller Manager (kube-controller-manager) died unexpectedly
```

Could you possibly point me to how these nodes are running? How can I gain access to them for debugging/inspecting?

**Comment by saschagrunert** [comment]
Hey @chrissound, the logs should be usually available in the directory `./kubernix-run/`, where each component has its own directory. So for the API Server the logs are available in: `./kubernix-run/apiserver/kube-apiserver.log`

**Comment by saschagrunert** [comment]
Closing. Feel free to reopen if you have further questions.
