### ISSUE TITLE
kubectl in the shell

### ISSUE THREAD

**Issue by vdemeester** [saschagrunert/kubernix#271]
The shell that `kubernix` drops us into doesn't have `kubectl` in. This means if my environment doesn't have it (my "root" on NixOS doesn't have `kubectl` installed so not in the path), I need to install it and / or use `nix run …`.

- I think it would be nice to have it
- It would also allow to ping the `kubectl` command to the `kubernetes` version (although it's not a requirement and doesn't have too much impact)

**Comment by saschagrunert** [comment]
Hey, yeah I agree. I’ll see how this can be fixed.
